version: "3.6"
services:
  app:
    build:
    context: ./.docker/app
    volumes:
      - ./:/app:delegated
    ports:
      - "443:443"
    environment:
    XDEBUG_ENABLE: 1
    XDEBUG_CONFIG: "remote_enable=1 remote_autostart=1 remote_connect_back=0 remote_host=docker.for.mac.localhost remote_handler=dbgp max_nesting_level=250 file_link_format='vscode://file/%f:%l&/app/project/'"
    PHP_IDE_CONFIG: "serverName=localhost"
    APP_AUTH_ENV: "test"
    APP_ENV: "dev"
    APP_DEBUG: 1
    DATABASE_URL: "mysql://app:app@db/app?serverVersion=5.7"
  db:
    image: mysql:5.7
    ports:
      - "33306:3306"
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
  mail:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
volumes:
  database:
    driver: local
networks:
  default:
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: 127.0.0.1
      com.docker.network.driver.mtu: 1400
